const Products = [
    {
      "id": "1",
      "name": "Apple IPhone 13 mini, 256Gb, RED",
      "year": "2021",
      "price": 3399,
      "amount": 2,
      "mainImg": "assets/images/0013500142-1.jpg",
      "imgOne": "assets/images/iphone13minione.png",
      "imgTwo": "assets/images/iphone13minitwo.png",
      "description": "A magical new way to interact with iPhone. Groundbreaking safety features designed to save lives. An innovative 48MP camera for mind-blowing detail. All powered by the ultimate smartphone chip.",
      "category": "Iphone",
      "discount": "15",
    },
    {
      "id": "2",
      "name": "Apple Air Pods Pro",
      "year": "2022",
      "price": 610,
      "amount": 12,
      "mainImg": "assets/images/005256222-1.jpg",
      "imgOne": "assets/images/podsproone.jpg",
      "imgTwo": "assets/images/podsprotwo.jpg",
      "description": "AirPods Pro have been reengineered for even richer audio experiences. Next-level Active Noise Cancellation and Adaptive Transparency reduce more external noise. Spatial Audio takes immersion to a remarkably personal level. Touch control now lets you adjust volume with a swipe. And a leap in power delivers 6 hours of battery life from a single charge.",
      "category": "Air Pods",
      "discount": "15",
    },
    {
      "id": "3",
      "name": "Apple IPhone 11, 64Gb, WHITE",
      "year": "2019",
      "price": 1599,
      "amount": 6,
      "mainImg": "assets/images/002356405-1.jpg",
      "imgOne": "assets/images/iphone11one.jpg",
      "imgTwo": "assets/images/iphone11two.jpg",
      "description": "A magical new way to interact with iPhone. Groundbreaking safety features designed to save lives. An innovative 48MP camera for mind-blowing detail. All powered by the ultimate smartphone chip.",
      "category": "Iphone",
      "discount": "25",
    },
    {
      "id": "4",
      "name": "Apple Watch Series 7, 41mm",
      "year": "2022",
      "price": 1199,
      "amount": 3,
      "mainImg": "assets/images/005306603-1.jpg",
      "imgOne": "assets/images/watch7one.png",
      "imgTwo": "assets/images/watch7two.png",
      "description": "A great deal to love. Powerful sensors for insights about your health and fitness. Innovative safety features. Convenient ways to stay connected. A faster dual-core processor for added performance. Apple Watch SE is feature packed, and now it’s a better value than ever.",
      "category": "Watch",
      "discount": "15",
    },
    {
      "id": "5",
      "name": "Apple IPhone 13 PRO MAX, 128Gb, WHITE ",
      "year": "2021",
      "price": 3420,
      "amount": 5,
      "mainImg": "assets/images/005300330-1.jpg",
      "imgOne": "assets/images/iphone13promax.png",
      "imgTwo": "assets/images/iphone13promax.png",
      "description": "A magical new way to interact with iPhone. Groundbreaking safety features designed to save lives. An innovative 48MP camera for mind-blowing detail. All powered by the ultimate smartphone chip.",
      "category": "Iphone",
      "discount": "15",
    },
    {
      "id": "6",
      "name": "Apple IPhone 13 PRO, 256Gb, BLUE",
      "year": "2021",
      "price": 3499,
      "amount": 5,
      "mainImg": "assets/images/005256308-1.jpg",
      "imgOne": "assets/images/iphone13proone.png",
      "imgTwo": "assets/images/phone13protwo.png",
      "description": "A magical new way to interact with iPhone. Groundbreaking safety features designed to save lives. An innovative 48MP camera for mind-blowing detail. All powered by the ultimate smartphone chip.",
      "category": "Iphone",
      "discount": "15",
    },
    {
      "id": "7",
      "name": "Apple IPhone 13, 256Gb, BLACK",
      "year": "2021",
      "price": 2799,
      "amount": 10,
      "mainImg": "assets/images/001350379-1.jpg",
      "imgOne": "assets/images/iphone13one.png",
      "imgTwo": "assets/images/iphone13two.png",
      "description": "A magical new way to interact with iPhone. Groundbreaking safety features designed to save lives. An innovative 48MP camera for mind-blowing detail. All powered by the ultimate smartphone chip.",
      "category": "Iphone",
      "discount": "15",
    },
    {
      "id": "8",
      "name": "Apple Watch SE, 44mm, WHITE",
      "year": "2020",
      "price": 998,
      "amount": 4,
      "mainImg": "assets/images/0014000223-1.jpg",
      "imgOne": "assets/images/watchseone.jpg",
      "imgTwo": "assets/images/watchsetwo.jpg",
      "description": "A great deal to love. Powerful sensors for insights about your health and fitness. Innovative safety features. Convenient ways to stay connected. A faster dual-core processor for added performance. Apple Watch SE is feature packed, and now it’s a better value than ever.",
      "category": "Watch",
      "discount": "20",
    },
    {
      "id": "9",
      "name": "Apple IPhone 12, 64Gb, BLACK",
      "year": "2020",
      "price": 1910,
      "amount": 12,
      "mainImg": "assets/images/001351025-1.jpg",
      "imgOne": "assets/images/iphone12one.jpg",
      "imgTwo": "assets/images/iphone12two.jpg",
      "description": "A magical new way to interact with iPhone. Groundbreaking safety features designed to save lives. An innovative 48MP camera for mind-blowing detail. All powered by the ultimate smartphone chip.",
      "category": "Iphone",
      "discount": "20",
    },
    {
      "id": "10",
      "name": "Apple IPhone 12 PRO, 128Gb, GRAPHITE",
      "year": "2020",
      "price": 2988,
      "amount": 0,
      "mainImg": "assets/images/005406210-1.jpg",
      "imgOne": "",
      "imgTwo": "",
      "description": "A magical new way to interact with iPhone. Groundbreaking safety features designed to save lives. An innovative 48MP camera for mind-blowing detail. All powered by the ultimate smartphone chip.",
      "category": "Iphone",
      "discount": "20",
    },
    {
      "id": "11",
      "name": "AirPods 2",
      "year": "2019",
      "price": 393,
      "amount": 7,
      "mainImg": "assets/images/001354609-1.jpg",
      "imgOne": "assets/images/pods2one.jpg",
      "imgTwo": "assets/images/pods2two.jpg",
      "description": "Wireless. Effortless. Magical. With plenty of talk and listen time, voice-activated Siri access, and an available wireless charging case, AirPods deliver an incredible wireless headphone experience. Simply take them out and they’re ready to use with all your devices. Put them in your ears and they connect immediately, immersing you in rich, high-quality sound. Just like magic.",
      "category": "Air Pods",
      "discount": "20",
    },
    {
      "id": "12",
      "name": "AirPods 3",
      "year": "2020",
      "price": 530,
      "amount": 8,
      "mainImg": "assets/images/001351026-1.jpg",
      "imgOne": "assets/images/pods3one.jpg",
      "imgTwo": "assets/images/pods3two.png",
      "description": "AirPods with Personalized Spatial Audio. Adaptive EQ that tunes music to your ears, and longer battery life that charges up in a snap. It shrugs off sweat and sprinkles, and delivers anexperience that’s simply magical.",
      "category": "Air Pods",
      "discount": "15",
    },
    {
      "id": "13",
      "name": "Apple IPhone 14, 256Gb, BLUE",
      "year": "2022",
      "price": 4899,
      "amount": 13,
      "mainImg": "assets/images/iphone14.png",
      "imgOne": "assets/images/iphone14one.png",
      "imgTwo": "assets/images/phone14two.png",
      "description": "A magical new way to interact with iPhone. Groundbreaking safety features designed to save lives. An innovative 48MP camera for mind-blowing detail. All powered by the ultimate smartphone chip.",
      "category": "Iphone",
      "discount": "10",
    },
    {
      "id": "14",
      "name": "Apple IPhone 14 PRO, 512Gb, PURPLE",
      "year": "2022",
      "price": 5399,
      "amount": 18,
      "mainImg": "assets/images/iphone14pro.png",
      "imgOne": "assets/images/iphone14proone.png",
      "imgTwo": "assets/images/iphone14protwo.jpg",
      "description": "A magical new way to interact with iPhone. Groundbreaking safety features designed to save lives. An innovative 48MP camera for mind-blowing detail. All powered by the ultimate smartphone chip.",
      "category": "Iphone",
      "discount": "10",
    },
    {
      "id": "15",
      "name": "Apple AirPods Max, SPACE GRAY",
      "year": "2022",
      "price": 1499,
      "amount": 7,
      "mainImg": "assets/images/airpods-max.jpg",
      "imgOne": "assets/images/podsmaxone.jpg",
      "imgTwo": "assets/images/podsmaxtwo.jpg",
      "description": "Introducing AirPods Max — a perfect balance of exhilarating high-fidelity audio and the effortless magic of AirPods. The ultimate personal listening experience is here.",
      "category": "Air Pods",
      "discount": "7",
    },
    {
      "id": "16",
      "name": "MacBook Air 13' Apple M1, 8Gb, 256Gb, SPACE GRAY",
      "year": "2022",
      "price": 3399,
      "amount": 9,
      "mainImg": "assets/images/macbookair.png",
      "imgOne": "assets/images/air13one.jpg",
      "imgTwo": "assets/images/air13two.jpg",
      "description": "MacBook Air with M1 is an incredibly portable laptop — it’s nimble and quick, with a silent, fanless design and a beautiful Retina display. Thanks to its slim profile and all‑day battery life, this Air moves at the speed of lightness.",
      "category": "Mac Book",
      "discount": "7",
    },
    {
      "id": "17",
      "name": "Apple MacBook Pro 16' with Touch Bar Intel Core i9, 16Gb, 1Tb, SILVER",
      "year": "2022",
      "price": 6799,
      "amount": 3,
      "mainImg": "assets/images/mbpro.jpg",
      "imgOne": "assets/images/pro16one.jpg",
      "imgTwo": "assets/images/pro16two.jpg",
      "description": "The most powerful MacBook Pro ever is here. With the blazing-fast M1 Pro or M1 Max chip — the first Apple silicon designed for pros — you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac laptop, and all the ports you need. The first notebook of its kind, this MacBook Pro is a beast.",
      "category": "Mac Book",
      "discount": "5",
    },
    {
      "id": "18",
      "name": "Apple Watch 8, 41mm, BLACK",
      "year": "2022",
      "price": 1499,
      "amount": 11,
      "mainImg": "assets/images/watch8.jpg",
      "imgOne": "assets/images/watch8one.png",
      "imgTwo": "assets/images/watch8two.png",
      "description": "Your essential companion is now even more powerful. Introducing temperature sensing for deeper insights into women’s health. Crash Detection to get help in an emergency. Sleep stages to better understand your sleep. And new ways to train using the enhanced Workout app. The future of health never looked so good.",
      "category": "Watch",
      "discount": "5",
    },
    {
      "id": "19",
      "name": "Apple Watch Ultra GPS + Cellular, 49mm, GRAY",
      "year": "2022",
      "price": 2699,
      "amount": 8,
      "mainImg": "assets/images/watchUltra.png",
      "imgOne": "assets/images/watchultraone.jpg",
      "imgTwo": "assets/images/watchultratwo.jpg",
      "description": "Meet the most rugged and capable Apple Watch ever. With a robust titanium case, precision dual-frequency GPS, up to 36 hours of battery life,1 the freedom of cellular,2 and three specialized bands made for athletes and adventurers of all kinds.",
      "category": "Watch",
      "discount": "5",
    },
    {
      "id": "20",
      "name": "Apple MacBook Pro 14' 16Gb, 512Gb, SILVER",
      "year": "2021",
      "price": 5499,
      "amount": 5,
      "mainImg": "assets/images/macbookpro14.jpg",
      "imgOne": "assets/images/pro14one.jpg",
      "imgTwo": "assets/images/pro14two.jpg",
      "description": "The most powerful MacBook Pro ever is here. With the blazing-fast M1 Pro or M1 Max chip — the first Apple silicon designed for pros — you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac laptop, and all the ports you need. The first notebook of its kind, this MacBook Pro is a beast.",
      "category": "Mac Book",
      "discount": "5",
    },
  ]
  export default Products;